name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Install Dependencies
        run: npm install
      
      - name: Build Android Release
        run: npm run build:android:release

      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: release
          path: android/app/build/outputs/apk/release/app-release.apk
      
